version: '3.6'

networks:
    network-gopostgres:
services:

    db:
        image: postgres
        restart: always
        networks:
            - 'network-gopostgres'
        environment:
            IP: 172.17.0.1
            PORT: 5432
            POSTGRES_URL:
            POSTGRES_PASSWORD: postgres
        volumes:
            - './data:/var/lib/postgresql/data'
    go:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["/bin/sh", "./a.out"]
        networks:
            - 'network-gopostgres'
        ports:
            - '8000:8000'
        depends_on:
            - 'db'

